#!/usr/bin/env python

Import('env')

my_incpath = []

env.core_sources = env.core_sources + env.Object(
    [
        'ParticleSystem.cpp',
        'ParticleData.cpp',
        'ShapeGenerator.cpp'
    ],
    CPPPATH=my_incpath
)
