#!/usr/bin/env python

Import('env')

my_incpath = []
my_ccflags = ['-O3', '-Wall', '-std=c++17']

env.core_sources = env.core_sources + env.Object(
    [
        'MarchingSq.cpp',
        'PolygonSimplify.cpp',
        'ConvexDecomp.cpp'
    ],
    CPPPATH=my_incpath,
    CCFLAGS=my_ccflags
)
