#!/usr/bin/env python

Import('env')

my_incpath = []

env.core_sources = env.core_sources + env.Object(
    [
        'Audio.cpp',
        'Sound.cpp',
        'Music.cpp'
    ],
    CPPPATH=my_incpath
)
