#!/usr/bin/env python

Import('env', 'config')

my_incpath = [config['paths']['freetype']]

env.core_sources = env.core_sources + env.Object(
    [
        'UISprite.cpp',
        'Button.cpp',
        'Font.cpp',
        'UI.cpp',
        'TextLabel.cpp',
    ],
    CPPPATH=my_incpath
)
